[package]
id = "qrv2fvzyqiwlzknckzbpeebenfqy4tnj"
name = "My Mod"
version = "0.0.1"
content = { type = "Mod", for_playables = ["g3zgnkhjpcuwjthi5vk5b5xvipbbcmtd"] }
ambient_version = "0.3.0-nightly-2023-10-02"

[dependencies]
my_game = { deployment = "47MheSj45Rjr1sVj8tSt0e" }
